use hyperdex::*;
use libc::{size_t, int64_t, uint64_t, uint16_t};

/* automatically generated by rust-bindgen */

pub enum Struct_hyperdex_admin { }
#[repr(C)]
pub struct Struct_hyperdex_admin_perf_counter {
    pub id: uint64_t,
    pub time: uint64_t,
    pub property: *const ::libc::c_char,
    pub measurement: uint64_t,
}
pub type Enum_hyperdex_admin_returncode = ::libc::c_uint;
pub static HYPERDEX_ADMIN_SUCCESS: ::libc::c_uint = 8704;
pub static HYPERDEX_ADMIN_NOMEM: ::libc::c_uint = 8768;
pub static HYPERDEX_ADMIN_NONEPENDING: ::libc::c_uint = 8769;
pub static HYPERDEX_ADMIN_POLLFAILED: ::libc::c_uint = 8770;
pub static HYPERDEX_ADMIN_TIMEOUT: ::libc::c_uint = 8771;
pub static HYPERDEX_ADMIN_INTERRUPTED: ::libc::c_uint = 8772;
pub static HYPERDEX_ADMIN_SERVERERROR: ::libc::c_uint = 8773;
pub static HYPERDEX_ADMIN_COORDFAIL: ::libc::c_uint = 8774;
pub static HYPERDEX_ADMIN_BADSPACE: ::libc::c_uint = 8775;
pub static HYPERDEX_ADMIN_DUPLICATE: ::libc::c_uint = 8776;
pub static HYPERDEX_ADMIN_NOTFOUND: ::libc::c_uint = 8777;
pub static HYPERDEX_ADMIN_LOCALERROR: ::libc::c_uint = 8778;
pub static HYPERDEX_ADMIN_INTERNAL: ::libc::c_uint = 8829;
pub static HYPERDEX_ADMIN_EXCEPTION: ::libc::c_uint = 8830;
pub static HYPERDEX_ADMIN_GARBAGE: ::libc::c_uint = 8831;
#[link(name = "hyperdex-admin")]
extern "C" {
    pub fn hyperdex_admin_create(coordinator: *const ::libc::c_char,
                                 port: uint16_t) ->
     *mut Struct_hyperdex_admin;
    pub fn hyperdex_admin_destroy(admin: *mut Struct_hyperdex_admin);
    pub fn hyperdex_admin_dump_config(admin: *mut Struct_hyperdex_admin,
                                      status:
                                          *mut Enum_hyperdex_admin_returncode,
                                      config: *mut *const ::libc::c_char) ->
     int64_t;
    pub fn hyperdex_admin_read_only(admin: *mut Struct_hyperdex_admin,
                                    ro: ::libc::c_int,
                                    status:
                                        *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_wait_until_stable(admin: *mut Struct_hyperdex_admin,
                                            status:
                                                *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_fault_tolerance(admin: *mut Struct_hyperdex_admin,
                                          space: *const ::libc::c_char,
                                          ft: uint64_t,
                                          status:
                                              *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_validate_space(admin: *mut Struct_hyperdex_admin,
                                         description: *const ::libc::c_char,
                                         status:
                                             *mut Enum_hyperdex_admin_returncode)
     -> ::libc::c_int;
    pub fn hyperdex_admin_add_space(admin: *mut Struct_hyperdex_admin,
                                    description: *const ::libc::c_char,
                                    status:
                                        *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_rm_space(admin: *mut Struct_hyperdex_admin,
                                   space: *const ::libc::c_char,
                                   status:
                                       *mut Enum_hyperdex_admin_returncode) ->
     int64_t;
    pub fn hyperdex_admin_mv_space(admin: *mut Struct_hyperdex_admin,
                                   source: *const ::libc::c_char,
                                   target: *const ::libc::c_char,
                                   status:
                                       *mut Enum_hyperdex_admin_returncode) ->
     int64_t;
    pub fn hyperdex_admin_list_spaces(admin: *mut Struct_hyperdex_admin,
                                      status:
                                          *mut Enum_hyperdex_admin_returncode,
                                      spaces: *mut *const ::libc::c_char) ->
     int64_t;
    pub fn hyperdex_admin_add_index(admin: *mut Struct_hyperdex_admin,
                                    space: *const ::libc::c_char,
                                    attribute: *const ::libc::c_char,
                                    status:
                                        *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_rm_index(admin: *mut Struct_hyperdex_admin,
                                   idxid: uint64_t,
                                   status:
                                       *mut Enum_hyperdex_admin_returncode) ->
     int64_t;
    pub fn hyperdex_admin_server_register(admin: *mut Struct_hyperdex_admin,
                                          token: uint64_t,
                                          address: *const ::libc::c_char,
                                          status:
                                              *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_server_online(admin: *mut Struct_hyperdex_admin,
                                        token: uint64_t,
                                        status:
                                            *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_server_offline(admin: *mut Struct_hyperdex_admin,
                                         token: uint64_t,
                                         status:
                                             *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_server_forget(admin: *mut Struct_hyperdex_admin,
                                        token: uint64_t,
                                        status:
                                            *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_server_kill(admin: *mut Struct_hyperdex_admin,
                                      token: uint64_t,
                                      status:
                                          *mut Enum_hyperdex_admin_returncode)
     -> int64_t;
    pub fn hyperdex_admin_backup(admin: *mut Struct_hyperdex_admin,
                                 backup: *const ::libc::c_char,
                                 status: *mut Enum_hyperdex_admin_returncode,
                                 backups: *mut *const ::libc::c_char) ->
     int64_t;
    pub fn hyperdex_admin_enable_perf_counters(admin:
                                                   *mut Struct_hyperdex_admin,
                                               status:
                                                   *mut Enum_hyperdex_admin_returncode,
                                               pc:
                                                   *mut Struct_hyperdex_admin_perf_counter)
     -> int64_t;
    pub fn hyperdex_admin_disable_perf_counters(admin:
                                                    *mut Struct_hyperdex_admin);
    pub fn hyperdex_admin_loop(admin: *mut Struct_hyperdex_admin,
                               timeout: ::libc::c_int,
                               status: *mut Enum_hyperdex_admin_returncode) ->
     int64_t;
    pub fn hyperdex_admin_raw_backup(host: *const ::libc::c_char,
                                     port: uint16_t,
                                     name: *const ::libc::c_char,
                                     status:
                                         *mut Enum_hyperdex_admin_returncode)
     -> ::libc::c_int;
    pub fn hyperdex_admin_error_message(admin: *mut Struct_hyperdex_admin) ->
     *const ::libc::c_char;
    pub fn hyperdex_admin_error_location(admin: *mut Struct_hyperdex_admin) ->
     *const ::libc::c_char;
    pub fn hyperdex_admin_returncode_to_string(arg1:
                                                   Enum_hyperdex_admin_returncode)
     -> *const ::libc::c_char;
}
